server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: smart-farming-api
  profiles:
    default: local

app:
  ml-service-url: ${ML_SERVICE_URL:http://127.0.0.1:8000}
  jwt-secret: ${JWT_SECRET:}
  weather-api-key: ${OPENWEATHER_API_KEY:}
